name: code-coverage-action
on: [push]
jobs:
    tests-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: pre-commit/action@v3.0.1
              with:
                node-version: 20
            - run: npm install -g jest
            - run: npm test
            